FROM nodered/node-red:1.3.3

USER root
ENV FLOWS=flows.json

RUN apk --no-cache add libaio libnsl libc6-compat curl && \
    cd /tmp && \
    curl -o instantclient-basic.zip https://download.oracle.com/otn_software/linux/instantclient/instantclient-basic-linuxx64.zip -SL && \
	curl -o instantclient-sqlplus.zip https://download.oracle.com/otn_software/linux/instantclient/instantclient-sqlplus-linuxx64.zip -SL && \
    unzip instantclient-basic.zip && \
	unzip instantclient-sqlplus.zip && \
	rm instantclient-basic.zip && \
	rm instantclient-sqlplus.zip && \
	mv instantclient*/ /usr/lib/instantclient && \
    ln -s /usr/lib/instantclient/libclntsh.so.19.1 /usr/lib/libclntsh.so && \
    ln -s /usr/lib/instantclient/libocci.so.19.1 /usr/lib/libocci.so && \
    ln -s /usr/lib/instantclient/libociicus.so /usr/lib/libociicus.so && \
    ln -s /usr/lib/instantclient/libnnz19.so /usr/lib/libnnz19.so && \
    ln -s /usr/lib/libnsl.so.2 /usr/lib/libnsl.so.1 && \
    ln -s /lib/libc.so.6 /usr/lib/libresolv.so.2 && \
    ln -s /lib64/ld-linux-x86-64.so.2 /usr/lib/ld-linux-x86-64.so.2 && \
	ln -s /usr/lib/instantclient/libsqlplus.so /usr/lib/libsqlplus.so && \
	ln -s /usr/lib/instantclient/libsqlplusic.so /usr/lib/libsqlplusic.so && \
	ln -s /usr/lib/instantclient/sqlplus /usr/lib/sqlplus

ENV ORACLE_BASE /usr/lib/instantclient
ENV LD_LIBRARY_PATH /usr/lib/instantclient
ENV TNS_ADMIN /usr/lib/instantclient
ENV ORACLE_HOME /usr/lib/instantclient

WORKDIR /usr/src/node-red
RUN npm install --unsafe-perm oracledb node-red-contrib-oracledb-mod

USER node-red
